### ISSUE TITLE
Support for other Linux distributions (namely arch)

### ISSUE THREAD

**Issue by wmlele** [hallard/ArduiPi_SSD1306#2]
I am trying to compile your library (the goal is ultimately to write a ruby wrapper for a project I am developing).

When compiling the example code I get into a 

```
[root@alarmpi examples]# make
g++ -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -Wall  -lssd1306 ssd1306_demo.cpp -o ssd1306_demo
/usr/local/lib/libssd1306.so: undefined reference to `i2c_smbus_write_i2c_block_data'
/usr/local/lib/libssd1306.so: undefined reference to `i2c_smbus_write_byte_data'
/usr/local/lib/libssd1306.so: undefined reference to `i2c_smbus_write_word_data'
collect2: error: ld returned 1 exit status
```

Which I find hard to understand, as those should be provided by the linux i2c subsystem.
Can you shed some light, please?

**Comment by AustinSaintAubin** [comment]
How did you resolve this? I am having the same issue...

**Comment by hallard** [comment]
Austin,
I think you need to install the following packages
`sudo apt-get install libi2c-dev i2c-tools`
then it should work, if not try to re install again (don't know why) then it worked for me, see comment on the official post
http://hallard.me/adafruit-ssd1306-oled-display-driver-for-raspberry-pi/

**Comment by AustinSaintAubin** [comment]
I am using Arch linux. I have i2c-tools & lm_sensors installed.
There does not seem to be a libi2c-dev package for Arch...

**Comment by sven337** [comment]
See my comment above, with a commit that shows what I did to fix the problem. Have you tried it?

**Comment by AustinSaintAubin** [comment]
Ah, edited ArduiPi_SSD1306 / bcm2835.c
Replaced: #include <linux/i2c-dev.h>
with: #include "./i2c-dev.h"

cd ArduiPi_SSD1306
make clean; make
cd examples
make clean; make

Now I have a new issue.
# ./ssd1306_demo --verbose --oled 3
./ssd1306_demo: error while loading shared libraries: libssd1306.so.1: cannot open shared object file: No such file or directory

**Comment by AustinSaintAubin** [comment]
# Got it working
Had to create softlink to missing lib.
```
ldd ssd1306_demo  # Show Dependencies
ln -s /usr/local/lib/libssd1306.so /usr/lib/libssd1306.so.1
```


# Here is my quick setup for anyone using Arch Linux.
```
# http://hallard.me/adafruit-ssd1306-oled-display-driver-for-raspberry-pi/
pacman -Sy --needed --noconfirm git make binutils gcc wget

# Download Repository
git clone https://github.com/hallard/ArduiPi_SSD1306.git
cd ArduiPi_SSD1306

# I2C - Development header files?
# https://github.com/hallard/ArduiPi_SSD1306/issues/2   https://github.com/sven337/RF24/commit/54f33151565cdd8925bd7f007b2c89cc251912a5
wget https://raw.githubusercontent.com/sven337/RF24/54f33151565cdd8925bd7f007b2c89cc251912a5/librf24-rpi/librf24-bcm/i2c-dev.h
sed -i 's/<linux\/i2c-dev\.h>/"\.\/i2c-dev\.h"/g' bcm2835.c  # Replace: #include <linux/i2c-dev.h> with: #include "./i2c-dev.h"

# Build Framework
make clean; make

# Make Softlink
# ldd ssd1306_demo  # Show Dependencies
ln -s /usr/local/lib/libssd1306.so /usr/lib/libssd1306.so.1

# Build Example
cd examples
make clean; make

# Run Example Code
./ssd1306_demo --verbose --oled 3
```
